spring:
  application:
    name: servicio-formaciones
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher #Para el swagger
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 3000  
