spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cursos?serverTimezone=UTC
    username: root
    password: Botsuana2976
  jpa:
    hibernate:
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  application:
    name: servicio-cursos
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher #Para el swagger
eureka:
  client:
      service-url:
        defaultZone: http://localhost:8761/eureka
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}      
server:
   port: ${PORT:0}
